/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e235713;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;

class RemingCardTest {
    @Test
    void remainingCardTest() {
        Player player = new Player("testPlayer");
        Bot bot = new Bot("testBot");

        Game game1 = new Game(player,bot);
        Game game2 = new Game(player,bot);
        Game game3 = new Game(player,bot);

        ArrayList<Game> gameList = new ArrayList<Game>();
        gameList.add(game1);
        gameList.add(game2);
        gameList.add(game3);

        for (Game game : gameList) {
            game.addHand(player);
            int remainingCard = game.remainCard();
            assertEquals(50, remainingCard);
        }
    }
}
